stages:
  load_data:
    cmd: python src/data/load_data.py
    deps:
      - src/data/load_data.py


  create_features:
    cmd: python src/data/create_features.py
    deps:
      - src/data/create_features.py
      - data/raw/train.csv
      - data/raw/test.csv
    outs:
      - data/processed/train_featured.pkl
      - data/processed/test_featured.pkl

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - data/processed/train_featured.pkl
    outs:
      - models/random_forest_model.pkl

  predict:
    cmd: python src/models/predict.py
    deps:
      - src/models/predict.py
      - models/random_forest_model.pkl
      - data/processed/test_featured.pkl
    outs:
      - predictions/test_predictions.csv
