stages:
  create_base_pipeline:
    cmd: python src/pipelines/create_features_and_base_pipeline.py
    outs:
      - artifacts/base_pipeline.pkl

  configure_and_fit:
    cmd: python src/pipelines/configure_and_fit_pipeline.py
    deps:
      - artifacts/base_pipeline.pkl
    outs:
      - artifacts/trained_pipeline.pkl

  predict:
    cmd: python src/pipelines/predict_pipeline.py
    deps:
      - artifacts/trained_pipeline.pkl
    outs:
      - data/predictions/
